function WaypointToolbox
% WAYPOINTTOOLBOX - Interface principale pour la boîte à outils de waypoints
%
% Cette application permet de:
% 1. Créer des trajectoires de waypoints de façon graphique
% 2. Visualiser des trajectoires existantes avec synchronisation temporelle
% 3. Convertir entre différents formats de waypoints
%
% Auteur: Claude AI

% Vérifier si la figure existe déjà
figHandle = findobj('Type', 'figure', 'Name', 'Waypoint Toolbox');
if ~isempty(figHandle)
    figure(figHandle); % Mettre la figure au premier plan
    return;
end

% Créer la fenêtre principale
mainFig = figure('Name', 'Waypoint Toolbox', 'NumberTitle', 'off', ...
    'Position', [200, 200, 600, 400], 'MenuBar', 'none', 'Toolbar', 'none');

% Créer un panel pour les boutons
buttonPanel = uipanel('Parent', mainFig, 'Title', 'Boîte à outils Waypoints', ...
    'Position', [0.05, 0.05, 0.9, 0.9]);

% Logo ou image d'en-tête (version texte simple)
uicontrol('Parent', buttonPanel, 'Style', 'text', ...
    'String', 'WAYPOINT TOOLBOX', ...
    'Position', [50, 300, 440, 30], ...
    'FontSize', 16, 'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');

% Description
uicontrol('Parent', buttonPanel, 'Style', 'text', ...
    'String', 'Outils pour la création, visualisation et conversion de trajectoires de drones', ...
    'Position', [50, 275, 440, 20], ...
    'HorizontalAlignment', 'center');

% Boutons principaux
btnEditor = uicontrol('Parent', buttonPanel, 'Style', 'pushbutton', ...
    'String', 'Éditeur de Waypoints', ...
    'Position', [150, 220, 300, 30], ...
    'Callback', @launchEditor, ...
    'FontSize', 12);

btnViewer = uicontrol('Parent', buttonPanel, 'Style', 'pushbutton', ...
    'String', 'Visualisateur Multi-Trajectoires', ...
    'Position', [150, 160, 300, 30], ...
    'Callback', @launchViewer, ...
    'FontSize', 12);

btnConverter = uicontrol('Parent', buttonPanel, 'Style', 'pushbutton', ...
    'String', 'Convertisseur de Formats', ...
    'Position', [150, 100, 300, 30], ...
    'Callback', @launchConverter, ...
    'FontSize', 12);

% Description des outils
editorDesc = uicontrol('Parent', buttonPanel, 'Style', 'text', ...
    'String', 'Créer et modifier des trajectoires avec manipulation directe des points', ...
    'Position', [120, 190, 310, 20], ...
    'HorizontalAlignment', 'center', 'ForegroundColor', [0.4 0.4 0.4]);

viewerDesc = uicontrol('Parent', buttonPanel, 'Style', 'text', ...
    'String', 'Visualiser plusieurs trajectoires synchronisées dans le temps', ...
    'Position', [120, 130, 310, 20], ...
    'HorizontalAlignment', 'center', 'ForegroundColor', [0.4 0.4 0.4]);

convDesc = uicontrol('Parent', buttonPanel, 'Style', 'text', ...
    'String', 'Convertir et transformer des fichiers de waypoints existants', ...
    'Position', [120, 70, 310, 20], ...
    'HorizontalAlignment', 'center', 'ForegroundColor', [0.4 0.4 0.4]);

% Pied de page
uicontrol('Parent', buttonPanel, 'Style', 'text', ...
    'String', 'v2.0', ...
    'Position', [430, 10, 30, 15], ...
    'HorizontalAlignment', 'right', ...
    'FontSize', 8);

% Fonctions de callback
    function launchEditor(~, ~)
        % Lancer l'éditeur de waypoints
        try
            EnhancedWaypointGUI();
        catch err
            errordlg(['Erreur lors du lancement de l''éditeur: ' err.message], 'Erreur');
        end
    end

    function launchViewer(~, ~)
        % Lancer le visualisateur de trajectoires
        try
            MultiTrajectoryVisualizer();
        catch err
            errordlg(['Erreur lors du lancement du visualisateur: ' err.message], 'Erreur');
        end
    end

    function launchConverter(~, ~)
        % Lancer le convertisseur de formats
        try
            WaypointConverter();
        catch err
            errordlg(['Erreur lors du lancement du convertisseur: ' err.message], 'Erreur');
        end
    end
end